export const COUNTRIES: Record<string, { name: string; flag: string }> = {
    CZE: { name: 'Czechia', flag: 'cz' },
    MEX: { name: 'Mexico', flag: 'mx' },
    PAR: { name: 'Paraguay', flag: 'py' },
    ZAF: { name: 'South Africa', flag: 'za' },
    KOR: { name: 'South Korea', flag: 'kr' },
    BIH: { name: 'Bosnia and Herzegovina', flag: 'ba' },
    CAN: { name: 'Canada', flag: 'ca' },
    QAT: { name: 'Qatar', flag: 'qa' },
    SUI: { name: 'Switzerland', flag: 'ch' },
    BRA: { name: 'Brazil', flag: 'br' },
    HAI: { name: 'Haiti', flag: 'ht' },
    MAR: { name: 'Morocco', flag: 'ma' },
    SCO: { name: 'Scotland', flag: 'gb-sct' },
    AUS: { name: 'Australia', flag: 'au' },
    TUR: { name: 'Turkey', flag: 'tr' },
    USA: { name: 'United States', flag: 'us' },
    CUW: { name: 'Curaçao', flag: 'cw' },
    ECU: { name: 'Ecuador', flag: 'ec' },
    GER: { name: 'Germany', flag: 'de' },
    CIV: { name: 'Ivory Coast', flag: 'ci' },
    JPN: { name: 'Japan', flag: 'jp' },
    NED: { name: 'Netherlands', flag: 'nl' },
    NGA: { name: 'Nigeria', flag: 'ng' },
    SWE: { name: 'Sweden', flag: 'se' },
    TUN: { name: 'Tunisia', flag: 'tn' },
    BEL: { name: 'Belgium', flag: 'be' },
    EGY: { name: 'Egypt', flag: 'eg' },
    IRN: { name: 'Iran', flag: 'ir' },
    NZL: { name: 'New Zealand', flag: 'nz' },
    CPV: { name: 'Cape Verde', flag: 'cv' },
    KSA: { name: 'Saudi Arabia', flag: 'sa' },
    ESP: { name: 'Spain', flag: 'es' },
    URU: { name: 'Uruguay', flag: 'uy' },
    FRA: { name: 'France', flag: 'fr' },
    IRQ: { name: 'Iraq', flag: 'iq' },
    NOR: { name: 'Norway', flag: 'no' },
    SEN: { name: 'Senegal', flag: 'sn' },
    ALG: { name: 'Algeria', flag: 'dz' },
    ARG: { name: 'Argentina', flag: 'ar' },
    AUT: { name: 'Austria', flag: 'at' },
    JOR: { name: 'Jordan', flag: 'jo' },
    COL: { name: 'Colombia', flag: 'co' },
    COD: { name: 'DR Congo', flag: 'cd' },
    POR: { name: 'Portugal', flag: 'pt' },
    UZB: { name: 'Uzbekistan', flag: 'uz' },
    CRO: { name: 'Croatia', flag: 'hr' },
    ENG: { name: 'England', flag: 'gb-eng' },
    GHA: { name: 'Ghana', flag: 'gh' },
    PAN: { name: 'Panama', flag: 'pa' },
};
